# Generated by Django 4.0.6 on 2022-07-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('javna_uprava', '0003_choice_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question_id',
        ),
    ]
