# Generated by Django 4.0.6 on 2022-07-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('javna_uprava', '0004_rename_question_choice_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='correct',
            new_name='correct_choice',
        ),
    ]
